import { useState } from "react";
import type { Message } from "./types/message";
import { Header } from "./components/layout/Header";
import { WelcomeContent } from "./components/content/WelcomeContent";
import { MessageDisplay } from "./components/content/MessageDisplay";
import { ChatWidget } from "./components/chat/ChatWidget";
import "./App.css";

function App() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [selectedMessage, setSelectedMessage] = useState<Message | null>(null);
  const [isChatOpen, setIsChatOpen] = useState(false);

  // Handle new message from user
  const handleSendMessage = (content: string) => {
    const userMessage: Message = {
      id: `msg-${Date.now()}`,
      content,
      timestamp: new Date(),
      sender: "user",
    };

    setMessages((prev) => [...prev, userMessage]);

    // Simulate bot response with custom properties
    setTimeout(() => {
      const botMessage: Message = {
        id: `msg-${Date.now()}-bot`,
        content: `I've analyzed your request: "${content}". Here are the harmonized data insights.`,
        timestamp: new Date(),
        sender: "bot",
        properties: {
          analysisType: "Unstructured Data Harmonization",
          confidence: 0.95,
          dataSource: "Customer Records",
          recordsProcessed: 1247,
          matchAccuracy: "94.2%",
        },
        htmlContent: `
          <div class="space-y-4">
            <h3 class="text-lg font-bold">Data Analysis Results</h3>
            <p>Your data has been successfully processed and harmonized.</p>
            <div class="bg-blue-50 p-4 rounded">
              <h4 class="font-semibold mb-2">Key Insights:</h4>
              <ul class="list-disc list-inside space-y-1">
                <li>1,247 customer records processed</li>
                <li>94.2% match accuracy achieved</li>
                <li>15 duplicate entries identified and merged</li>
                <li>Data quality score: 95%</li>
              </ul>
            </div>
            <p class="text-sm text-gray-600">Generated by Agentforce at ${new Date().toLocaleTimeString()}</p>
          </div>
        `,
      };
      setMessages((prev) => [...prev, botMessage]);
    }, 1000);
  };

  // Handle message click
  const handleMessageClick = (message: Message) => {
    if (message.properties || message.htmlContent) {
      setSelectedMessage(message);
      setIsChatOpen(false); // Optionally close chat when viewing message details
    }
  };

  // Handle back to welcome
  const handleBackToWelcome = () => {
    setSelectedMessage(null);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <Header />

      <main>
        {selectedMessage ? (
          <MessageDisplay message={selectedMessage} onBack={handleBackToWelcome} />
        ) : (
          <WelcomeContent />
        )}
      </main>

      <ChatWidget
        messages={messages}
        onMessageClick={handleMessageClick}
        onSendMessage={handleSendMessage}
        isOpen={isChatOpen}
        onToggle={() => setIsChatOpen(!isChatOpen)}
      />
    </div>
  );
}

export default App;
